project:
  type: website
  output-dir: docs

website:
  favicon: "favicon.png"
  navbar:
    logo: images/navbar.png
    right:
      - faq.qmd
      - icon: github
        href: https://github.com/jazznbass/os-in-sed-blog/
format:
  html:
    theme: sandstone
    css: styles.css



