project:
  type: website
  output-dir: docs

website:
  title: "OS in SED"
  navbar:
    right:
      - discuss.qmd
      - about.qmd
      - icon: github
        href: https://github.com/jazznbass/os-in-sed-blog/
format:
  html:
    theme: cosmo
    css: styles.css



